2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_setup.py:_flush():67] Configure stats pid to 33339
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_setup.py:_flush():67] Loading settings from /Users/gichanpark/.config/wandb/settings
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_setup.py:_flush():67] Loading settings from /Users/gichanpark/Desktop/castone_design/wandb/settings
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/gichanpark/Desktop/castone_design/wandb/run-20250613_010206-tniolwsu/logs/debug.log
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/gichanpark/Desktop/castone_design/wandb/run-20250613_010206-tniolwsu/logs/debug-internal.log
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_init.py:init():761] calling init triggers
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 8, 'data_path': './finger_printing/datasets/train_dataset_augmented_selective_1.0.csv', 'dropout_rate': 0.3, 'early_stopping': False, 'embedding_dim': 32, 'epochs': 250, 'learning_rate': 0.0005, 'scheduler': True, 'transformer_heads': 2, 'transformer_layers': 3}
config: {'_wandb': {}}
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_init.py:init():784] starting backend
2025-06-13 01:02:06,692 INFO    Thread-3  :33339 [wandb_init.py:init():788] sending inform_init request
2025-06-13 01:02:06,732 INFO    Thread-3  :33339 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-06-13 01:02:06,732 INFO    Thread-3  :33339 [wandb_init.py:init():798] backend started and connected
2025-06-13 01:02:06,733 INFO    Thread-3  :33339 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 8, 'data_path': './finger_printing/datasets/train_dataset_augmented_selective_1.0.csv', 'dropout_rate': 0.3, 'early_stopping': False, 'embedding_dim': 32, 'epochs': 250, 'learning_rate': 0.0005, 'scheduler': True, 'transformer_heads': 2, 'transformer_layers': 3}
2025-06-13 01:02:06,736 INFO    Thread-3  :33339 [wandb_init.py:init():891] updated telemetry
2025-06-13 01:02:06,754 INFO    Thread-3  :33339 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-06-13 01:02:07,262 INFO    Thread-3  :33339 [wandb_init.py:init():990] starting run threads in backend
2025-06-13 01:02:07,346 INFO    Thread-3  :33339 [wandb_run.py:_console_start():2375] atexit reg
2025-06-13 01:02:07,346 INFO    Thread-3  :33339 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-06-13 01:02:07,347 INFO    Thread-3  :33339 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-06-13 01:02:07,347 INFO    Thread-3  :33339 [wandb_run.py:_redirect():2315] Redirects installed.
2025-06-13 01:02:07,349 INFO    Thread-3  :33339 [wandb_init.py:init():1032] run started, returning control to user process
2025-06-13 01:09:26,592 INFO    Thread-3  :33339 [wandb_run.py:_finish():2112] finishing run dguyanglab/wifi-fingerprinting/tniolwsu
2025-06-13 01:09:26,592 INFO    Thread-3  :33339 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 1
2025-06-13 01:09:26,592 INFO    Thread-3  :33339 [wandb_run.py:_restore():2322] restore
2025-06-13 01:09:26,592 INFO    Thread-3  :33339 [wandb_run.py:_restore():2328] restore done
2025-06-13 01:09:27,608 INFO    MsgRouterThr:33339 [mailbox.py:close():129] Closing mailbox, abandoning 2 handles.
2025-06-13 01:09:27,609 INFO    Thread-3  :33339 [wandb_run.py:_restore():2322] restore
2025-06-13 01:09:27,609 INFO    Thread-3  :33339 [wandb_run.py:_restore():2328] restore done
2025-06-13 01:09:27,609 ERROR   Thread-3  :33339 [wandb_run.py:_atexit_cleanup():2361] Problem finishing run
Traceback (most recent call last):
  File "/Users/gichanpark/Desktop/castone_design/finger_printing/train/train_CNNTransformer_sweep.py", line 190, in train_model
    outputs = model(rssi_batch, mac_batch)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/gichanpark/Desktop/castone_design/finger_printing/models/model_CNNTransformer.py", line 41, in forward
    x = self.dropout(x)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/torch/nn/functional.py", line 1266, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2352, in _atexit_cleanup
    self._on_finish()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 2609, in _on_finish
    wait_with_progress(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/lib/asyncio_compat.py", line 74, in run
    return asyncio.run(self._run_or_cancel(fn))
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/lib/asyncio_compat.py", line 98, in _run_or_cancel
    return fn_task.result()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 82, in progress_loop_with_timeout
    return await _wait_handles_async(
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 132, in _wait_handles_async
    task_group.start_soon(wait_single(index))
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/contextlib.py", line 178, in __aexit__
    await self.gen.__anext__()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/lib/asyncio_compat.py", line 190, in open_task_group
    await task_group._wait_all()
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/lib/asyncio_compat.py", line 159, in _wait_all
    raise exc
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 128, in wait_single
    results[index] = await handle.wait_async(timeout=timeout)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/mailbox_handle.py", line 126, in wait_async
    response = await self._handle.wait_async(timeout=timeout)
  File "/opt/homebrew/anaconda3/envs/capstone/lib/python3.8/site-packages/wandb/sdk/mailbox/response_handle.py", line 128, in wait_async
    raise HandleAbandonedError()
wandb.sdk.mailbox.mailbox_handle.HandleAbandonedError
